root: true
env:
  browser: true
  es2022: true
extends:
  - htmlacademy/vanilla
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'

globals:
  noUiSlider: readonly
  Pristine: readonly

rules:
  indent: [error, tab]
